DELETE FROM DateTimeBlockDetails;
DELETE FROM PictureBlockDetails;
DELETE FROM TableBlockColumnWidths;
DELETE FROM TableBlockRowHeights;
DELETE FROM TableCells;
DELETE FROM TableBlockRowDetails;
DELETE FROM TableBlockDetails;
DELETE FROM TextBlockDetails;
DELETE FROM DisplayBlocks WHERE Type<>'Scenario';
DELETE FROM Scenes;
DELETE FROM ScenarioDetails;
DELETE FROM DisplayBlocks;